qc:
	/home/olga/miniconda3/envs/DeNovoPipeline/bin/deNovo_pipeline.py  --global-config global.yml --sample-config quality_control.yml

assemble:
	/home/olga/miniconda3/envs/DeNovoPipeline/bin/deNovo_pipeline.py --global-config global.yml --sample-config assemble.yml
